// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCInFogROi5WkVi7fgnny8hsNb5oBZszWk',
    appId: '1:305327760297:web:0638ee23b5794ead1b9ab8',
    messagingSenderId: '305327760297',
    projectId: 'testing-cli-25f7b',
    authDomain: 'testing-cli-25f7b.firebaseapp.com',
    storageBucket: 'testing-cli-25f7b.firebasestorage.app',
    measurementId: 'G-7QKT8715KL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVV9zQSS7kOIu91O6O90bl9-z-gJq5Krk',
    appId: '1:305327760297:android:d4f78121029aa4961b9ab8',
    messagingSenderId: '305327760297',
    projectId: 'testing-cli-25f7b',
    storageBucket: 'testing-cli-25f7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhqBLQNLqLoLTcepRl77xxEFG_yR6UzF0',
    appId: '1:305327760297:ios:a11e81f8474329761b9ab8',
    messagingSenderId: '305327760297',
    projectId: 'testing-cli-25f7b',
    storageBucket: 'testing-cli-25f7b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhqBLQNLqLoLTcepRl77xxEFG_yR6UzF0',
    appId: '1:305327760297:ios:a11e81f8474329761b9ab8',
    messagingSenderId: '305327760297',
    projectId: 'testing-cli-25f7b',
    storageBucket: 'testing-cli-25f7b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCInFogROi5WkVi7fgnny8hsNb5oBZszWk',
    appId: '1:305327760297:web:adf9f78669a1d3801b9ab8',
    messagingSenderId: '305327760297',
    projectId: 'testing-cli-25f7b',
    authDomain: 'testing-cli-25f7b.firebaseapp.com',
    storageBucket: 'testing-cli-25f7b.firebasestorage.app',
    measurementId: 'G-M0PZSQQ02H',
  );
}
